name: flutter_projects
description: "Erişilebilir, sesli yönlendirmeli çocuklara özel eğitim oyunu."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  shared_preferences: ^2.2.0
  path: any
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  lottie: ^3.2.0





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/space_animation.json
    - assets/animations/sound_backk.json
    - assets/animations/celebrate.json
    - assets/animations/celebrate_baykus.json
    - assets/animations/back_arrow.json
    - assets/animations/bee_transition.json
    - assets/animations/alien_transition.json

    - assets/gif/bgg.gif
    - assets/gif/back.gif

    - assets/images/levelscreen_background.png
    - assets/audio/hosgeldin.mp3
    #Match planet
    - assets/images/kirmizi_cicek.png
    - assets/images/sari_araba.png
    - assets/images/siyah_kedi.png
    - assets/images/yesil_armut.png
    - assets/images/mavi_yildiz.png
    - assets/images/yesil_kurbaga.png
    - assets/images/pembe_ucgen.png
    - assets/images/red_balloon.png
    - assets/images/turuncu_top.png
    - assets/audio/kirmizi_cicek.mp3
    - assets/audio/sari_araba.mp3
    - assets/audio/mavi_yildiz.mp3
    - assets/audio/siyah_kedi.mp3
    - assets/audio/yesil_armut.mp3
    - assets/audio/kirmizi_balon.mp3
    - assets/audio/turuncu_top.mp3
    - assets/audio/yesil_kurbaga.mp3
    - assets/audio/pembe_ucgen.mp3
    - assets/audio/tebrikler.mp3
    - assets/images/planet_turquoise.png
    - assets/images/planet_yellow.png
    - assets/images/planet_white.png
    - assets/images/levelsec_back.png
    - assets/images/gezegen_kartlar.png

    - assets/audio/ses_gezegeni.mp3
    - assets/audio/eslestirme_gezegeni.mp3
    - assets/audio/eslestirme_basarili.mp3
    - assets/audio/tekrar_dene.mp3


    #Sound planet
    - assets/audio/animals_sound/correct_antelope.mp3
    - assets/audio/animals_sound/correct_bat.mp3
    - assets/audio/animals_sound/correct_cat.mp3
    - assets/audio/animals_sound/correct_cow.mp3
    - assets/audio/animals_sound/correct_dog.mp3
    - assets/audio/animals_sound/correct_duck.mp3
    - assets/audio/animals_sound/correct_elephant.mp3
    - assets/audio/animals_sound/correct_bee.mp3
    - assets/audio/animals_sound/correct_hen.mp3
    - assets/audio/animals_sound/correct_rooster.mp3
    - assets/audio/animals_sound/correct_sheep.mp3
    - assets/audio/game2_tekrar_dene.mp3
    - assets/audio/neyin_sesi.mp3

    - assets/audio/vehicle/airplane.mp3
    - assets/audio/vehicle/ambulance.mp3
    - assets/audio/vehicle/car.mp3
    - assets/audio/vehicle/firetruck.mp3
    - assets/audio/vehicle/helicopter.mp3
    - assets/audio/vehicle/police.mp3
    - assets/audio/vehicle/tractor.mp3
    - assets/audio/vehicle/train.mp3
    - assets/audio/vehicle/tram.mp3
    - assets/audio/vehicle/ship.mp3
    - assets/audio/vehicle/motorcycle.mp3
    - assets/audio/vehicle/submarine.mp3
    - assets/audio/vehicle/correct_airplane.mp3
    - assets/audio/vehicle/correct_ambulance.mp3
    - assets/audio/vehicle/correct_firetruck.mp3
    - assets/audio/vehicle/correct_helicopter.mp3
    - assets/audio/vehicle/correct_motorcycle.mp3
    - assets/audio/vehicle/correct_policecar.mp3
    - assets/audio/vehicle/correct_tractor.mp3
    - assets/audio/vehicle/correct_train.mp3
    - assets/audio/vehicle/correct_tram.mp3
    - assets/audio/vehicle/correct_car.mp3
    - assets/audio/vehicle/correct_ship.mp3
    - assets/audio/vehicle/correct_submarine.mp3
    - assets/audio/vehicle/sci-fi.mp3

    - assets/images/deer.png
    - assets/images/wolf.png
    - assets/images/goose.png
    - assets/images/goat.png
    - assets/images/housefly.png
    - assets/images/bird.png
    - assets/images/cat.png
    - assets/images/cow.png
    - assets/images/dog.png
    - assets/images/horse.png
    - assets/images/hen.png
    - assets/images/antelope.png
    - assets/images/bat.png
    - assets/images/bee.png
    - assets/images/duck.png
    - assets/images/elephant.png
    - assets/images/camel.png
    - assets/images/crocodile.png
    - assets/images/dolphin.png
    - assets/images/sheep.png
    - assets/images/rooster.png
    - assets/images/soundplanet1.png
    - assets/images/soundplanet2.png
    - assets/images/levelsecsound_bg.png
    - assets/images/game2_back.png
    - assets/images/void_planet.png

    - assets/images/planet2/airplane.png
    - assets/images/planet2/ambulance.png
    - assets/images/planet2/car.png
    - assets/images/planet2/firetruck.png
    - assets/images/planet2/helicopter.png
    - assets/images/planet2/motorcycle.png
    - assets/images/planet2/policecar.png
    - assets/images/planet2/tractor.png
    - assets/images/planet2/train.png
    - assets/images/planet2/tram.png
    - assets/images/planet2/ship.png
    - assets/images/planet2/submarine.png








  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
