// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1vJkNOVtg58iZBGl-M1C928AYFJjLmU',
    appId: '1:609448429265:web:2a295e188d673e998967f0',
    messagingSenderId: '609448429265',
    projectId: 'spaceedugame',
    authDomain: 'spaceedugame.firebaseapp.com',
    storageBucket: 'spaceedugame.firebasestorage.app',
    measurementId: 'G-3YR8QDCJL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChq5xJLOIevJiSm2NVyLAra6UAFjY_Xkk',
    appId: '1:609448429265:android:6d60c40b9220ddca8967f0',
    messagingSenderId: '609448429265',
    projectId: 'spaceedugame',
    storageBucket: 'spaceedugame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-9V4G9CrI_cpfe7sqTxJ6aXL_BM9mTZQ',
    appId: '1:609448429265:ios:61cd8fdd65b6a67c8967f0',
    messagingSenderId: '609448429265',
    projectId: 'spaceedugame',
    storageBucket: 'spaceedugame.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-9V4G9CrI_cpfe7sqTxJ6aXL_BM9mTZQ',
    appId: '1:609448429265:ios:61cd8fdd65b6a67c8967f0',
    messagingSenderId: '609448429265',
    projectId: 'spaceedugame',
    storageBucket: 'spaceedugame.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1vJkNOVtg58iZBGl-M1C928AYFJjLmU',
    appId: '1:609448429265:web:addfebad01b84ecd8967f0',
    messagingSenderId: '609448429265',
    projectId: 'spaceedugame',
    authDomain: 'spaceedugame.firebaseapp.com',
    storageBucket: 'spaceedugame.firebasestorage.app',
    measurementId: 'G-T6LH7H075F',
  );
}
